### ISSUE TITLE
Hot reload breaks with webpack

### ISSUE THREAD

**Issue by IlyaSemenov** [whitecolor/ts-node-dev#37] opened 2018-10-04 08:07 UTC
If the script runs webpack build, ts-node-dev's reload stops working. It detects that a module has changed, but doesn't really restart the app.

### Steps to reproduce

In empty directory, run `yarn add nuxt ts-node-dev typescript`, create `test.ts`:

```ts
import { Nuxt, Builder } from 'nuxt'

console.log('Loading...')

const nuxt = new Nuxt({ dev: false })
nuxt.listen(3000)

const builder = new Builder(nuxt)
// builder.build() // <--- Uncommenting this line breaks ts-node-dev's reload.

console.log(`Listening since ${new Date()}.`)
```

then run: `npx ts-node-dev test`

### Actual behaviour

`ts-node-dev` will restart the server when the file is modified. However, once `builder.build()` is uncommented, it will no more react on file changes.

Example output:

```
❯ npx ts-node-dev test
Loading...
Listening since Thu Oct 04 2018 14:48:44 GMT+0700 (Novosibirsk Standard Time).
[INFO] 14:48:55 Restarting: /Users/semenov/tmp/ts2/test.ts has been modified
Loading...
L1istening since Thu Oct 04 2018 14:48:57 GMT+0700 (Novosibirsk Standard Time).
[INFO] 14:49:01 Restarting: /Users/semenov/tmp/ts2/test.ts has been modified
Loading...
Listening since Thu Oct 04 2018 14:49:03 GMT+0700 (Novosibirsk Standard Time).
[INFO] 14:49:09 Restarting: /Users/semenov/tmp/ts2/test.ts has been modified
Loading...


 INFO  Building project

Listening since Thu Oct 04 2018 14:49:11 GMT+0700 (Novosibirsk Standard Time).
✔ success Builder initialized
✔ success Nuxt files generated


 READY  Listening on http://:::3000

[INFO] 14:49:40 Restarting: /Users/semenov/tmp/ts2/test.ts has been modified
```

^^^ after that it's stuck.

### Expected

`ts-node-dev` continues to reload if `test.ts` is modified.

---

The same problem happens not only with Nuxt but with Ream, so I believe it's caused by webpack4 which is used by both. I think it is **not** caused by webpack's Hot Module Reload as it repeats even with `{ dev: false }` which I believe disables HMR (but I'm not 100% sure in that).

**Comment by whitecolor** [comment] 2018-10-16 23:08
Really not sure I get the problem, I use `ts-node-dev` to run webpack-dev-server (via API), without any problems. I'm not even sure how can does webpack inner logic can effect ts-nod-dev behavior.

If you could create just a repo to reproduce it (that I would just clone and run npm install/npm run) I would check it.

**Comment by IlyaSemenov** [comment] 2018-10-17 02:50
Did you try the steps above? It's really about running one `npm install` and creating one file.

I'll create the reproduction repository but it's not going to be different from the above.

**Comment by whitecolor** [comment] 2018-10-18 15:34
I'm not sure, I seem to have no issues with restart on `test.ts` change

![image](https://user-images.githubusercontent.com/736697/47166264-2c8cd080-d315-11e8-862e-ef09c52eb2a0.png)

**Comment by IlyaSemenov** [comment] 2018-10-18 16:21
That's odd. I have this 100% reproducible. It could be related to the OS, I have only tested this on OS X. I will test on Ubuntu and report additionally.

**Comment by IlyaSemenov** [comment] 2018-10-26 16:53
I tested it on Linux and it gets stuck the same way as on OS X. Below is what happened when I ran `test.ts` unmodified from the reproduction repo then edited it once (as you can see on the screenshot it 'wanted' to restart but failed), then I edited `test.ts` many times more but the script didn't react, and then I finally pressed ^C.

<img width="912" alt="screenshot 2018-10-26 at 23 50 31" src="https://user-images.githubusercontent.com/128121/47580776-f638fc00-d979-11e8-9b96-5105da6bc594.png">

So even if it works on MS Windows there's still a problem with (probably) most other OS'es.

**Comment by whitecolor** [comment] 2018-11-18 01:05
Just tried it in WSL bash and inside the docker. Seems to be the problem with killing the child...
![image](https://user-images.githubusercontent.com/736697/48667437-3e6db900-eaf7-11e8-81c0-61e761638eb0.png)

Not sure what to do with that, something inside the `Nuxt` process. Note that in Windows it works ok.

**Comment by IlyaSemenov** [comment] 2018-11-18 06:42
Note that it's the same problem in Ream (https://ream.js.org) that's why I generalized it to webpack (or even Vue specifically?) and not to Nuxt.

**Comment by whitecolor** [comment] 2018-11-18 08:59
Well I'm building my webpack (just updated to 4) apps without problems, but I just use webpack API for running dev-server without wrappers. 

In your case, something inside doesn't want to die when SIGTERM send. Btw I just had such case with webpack build (while upgrading to WP4) it happened because of the long sync loop inside the build process (due some flawed logic of custom builder), when it ended (usually) process exited. So surely it is possible to debug it, but need to get into the source and do it.

**Comment by heralight** [comment] 2018-12-15 20:13
it's probably due to MacOS error: -67062 (in mac console) ... it's look like related to bin signature and listening file change... in my case, more strange refresh work if start up have an error, but not refresh when I get a state with no error.

**Comment by IlyaSemenov** [comment] 2018-12-16 02:46
As I mentioned above, it's exactly the same problem on Ubuntu, so it's unlikely has to do with a MacOS error.

**Comment by whitecolor** [comment] 2019-05-02 12:49
Will close it for now.

**Closed** 2019-05-02 12:49 UTC
