### ISSUE TITLE
Compilation errors are unseeable when you use ts-node 8.6.0+.

### ISSUE THREAD

**Issue by gipcompany** [whitecolor/ts-node-dev#119] opened 2020-01-23 14:32 UTC
I found that I was unable to see compilation errors when I used ts-node 8.6.0+ like below.

I don't know why, but I seem that I have to use ts-node lower than v8.6.0 if I use ts-node-dev.

### Using ts-node version 8.5.4

```
$ npx ts-node-dev src/boolean.ts
Using ts-node version 8.5.4, typescript version 3.7.5
[ERROR] 23:15:08 ⨯ Unable to compile TypeScript:
src/boolean.ts:7:1 - error TS2322: Type '1' is not assignable to type 'boolean'.

7 isFinished = 1;
  ~~~~~~~~~~
```

### Using ts-node version 8.6.0

```
$ npx ts-node-dev src/boolean.ts
Using ts-node version 8.6.0, typescript version 3.7.5
{ isFinished: 1 }
```

### `src/boolean.ts`

```typescript
let isFinished: boolean = true;
isFinished = 1;
console.log({ isFinished });
```

**Comment by andreisergiu98** [comment] 2020-02-03 09:12
I have the same problem, it transpiles correctly, but ignores type errors. I am not using the --transpileOnly flag. Also i can confirm that it works as expected with ts-node 8.5.4. 
I am using yarn so i created a resolution that temporarily fixed the problem.
```javascript
  "resolutions": {
    "ts-node-dev/ts-node": "8.5.4"
  }
```

**Comment by max10rogerio** [comment] 2020-02-03 16:59
> I have the same problem, it transpiles correctly, but ignores type errors. I am not using the --transpileOnly flag. Also i can confirm that it works as expected with ts-node 8.5.4.
> I am using yarn so i created a resolution that temporarily fixed the problem.
> 
> ```js
>   "resolutions": {
>     "ts-node-dev/ts-node": "8.5.4"
>   }
> ```

Nice!

**Comment by andreisergiu98** [comment] 2020-02-04 15:07
I found the problem. This commit added backward compatibility with an old (i think), deprecated, flag `--type-check` https://github.com/TypeStrong/ts-node/commit/8834d645849f5b9a6eb377aaa32e92dc094d40f8. When ts-node-dev initializes its options, if this flag is missing, it becomes `false` by default, which as a consequence disables type checking. If you add the `--type-check` flag, then type checking is working.
As a fix i think we should remove this option completely, we can also make it `true` by default, but since it's deprecated...
@whitecolor what do you suggest?

**Comment by wsmd** [comment] 2020-05-14 06:40
Also worth noting that when I run `tsnd` globally (`npm -i -g` / `yarn global add`), it behaves differently than when it's installed as a dependency in a project (`node_modules/.bin/tsnd`). For some reason the global instance respects type-checking but the project scoped one doesn't 😕 (both instances are the same version `1.0.0-pre.44`).

**Comment by andreisergiu98** [comment] 2020-05-14 08:37
@wsmd You might have an older version of ts-node installed globally?

**Comment by wsmd** [comment] 2020-05-14 16:32
That's a really good guess, unfortunately, ts-node in both locations is at `8.10.1`. Also, fwiw, both global and local typescript/tsc are also the same version, and I'm using yarn.

```sh
> /path/to/global/.bin/tsnd --version
v8.10.1
```

```sh
> /path/to/my_project/node_modules/.bin/ts-node --version
v8.10.1
```

**Comment by whitecolor** [comment] 2020-06-13 13:54
Will be fixed in the nearest published.

**Closed by whitecolor** 2020-06-13 13:54 UTC
